name: mtatracker

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install pytz
        pip install plotly
        pip install numpy

    - name: Run mta2.py
      run: |
        python ./mta3.py

    - name: Git push
      run: |
        git add .
        git commit -m "update"
        git push 
